services:
  - type: web
    name: omnisette
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: /app/omnisette-server --http-port $PORT --https-port 8443 -l Info
    envVars:
      - key: PORT
        value: 10000
    plan: free
